Feat/dq improve current icons in the stepper
EyeSeeTea/data-quality-dev pull request #42
Opened 2024-04-08 09:33 UTC by mariaozamiz

### :pushpin: References

-   **Issue:** Closes [DQ: Improve current icons in the Stepper](https://app.clickup.com/t/86947x6dc)
- CU-86947x6dc

### :memo: Implementation

The color scheme is supposed to work like this:
- The step is either pending of analysis or active --> grey background
- The step has unresolved issues --> red background
- The step has no issues --> green background

As client is about to check the app, I left some classes there just in case there is need of changing the color scheme. 

### :video_camera: Screenshots/Screen capture
<img width="920" alt="Captura de pantalla 2024-04-09 a las 14 14 12" src="https://github.com/EyeSeeTea/data-quality-dev/assets/55712984/e67070c4-c2b4-46ca-83dc-497df6d60d55">

### :fire: Notes to the tester

2024-04-08 09:33 UTC, ifoche commented
Task linked: [CU-86947x6dc DQ: Improve current icons in the Stepper](https://app.clickup.com/t/86947x6dc)

2024-04-09 13:55 UTC, Ramon-Jimenez requested changes
Only one small change, when step is active but it has been run, keep the bold but also the red/green colors.

So by using text in bold we represent the active step and by using grey/red/green we represent steps not run/issues found/issues not found.

If this doesn't make sense, let's quickly catch up on Slack. Thanks @mariaozamiz !

2024-04-09 19:33 UTC, eperedo requested changes
Thanks @mariaozamiz. A couple of observations about improving code readability, feel free to ask me any questions about it.

2024-04-09 19:33 UTC, eperedo commented on src/webapp/pages/analysis/AnalysisPage.tsx
> +            const isPending = section.status === "pending";
we can keep the method but without the NOT (!) operator.

```
const isPending = QualityAnalysisSection.isPending(section);
```

2024-04-09 19:33 UTC, eperedo commented on src/webapp/pages/analysis/AnalysisPage.tsx
> +    if (isPending) {
Here we're returning the same component but with different className. I think it's easier to read if we have a method to calculate the classes and just return the same component.

```tsx

function StepIcon(...) {
    const buildIconClasses = React.useMemo(() => {
        const baseClasses = [classes.circle];

        if (active) {
            return [...baseClasses, classes.active].join(" ");
        } else if (isPending) {
            return [...baseClasses, classes.pending].join(" ");
        } else if (hasIssues) {
            return [...baseClasses, classes.error].join(" ");
        } else {
            return [...baseClasses, classes.completed].join(" ");
        }
    }, [classes, active, hasIssues, isPending]);

    return <div className={buildIconClasses}>{text}</div>;
}

```

2024-04-10 11:31 UTC, Ramon-Jimenez approved these changes
Thx @mariaozamiz  looks OK to me

2024-04-10 17:05 UTC, eperedo approved these changes

2024-04-11 05:38 UTC, merged