fixed period range for datavalues endpoint
EyeSeeTea/data-quality-dev pull request #62
Opened 2024-10-25 14:02 UTC by eperedo

### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/8696c24p6

### :memo: Implementation

### :video_camera: Screenshots/Screen capture

### :fire: Notes to the tester

#8696c24p6

2024-10-25 14:02 UTC, ifoche commented
Task linked: [CU-8696c24p6 Bug: App not searching for years within a range, at least for Disaggregates step](https://app.clickup.com/t/8696c24p6)

2024-10-28 10:46 UTC, Ramon-Jimenez approved these changes
Thanks @eperedo

2024-10-29 08:45 UTC, Ramon-Jimenez requested changes
@eperedo if you select 2000 - 2023 period, it gives you an array out of length exception:

![image](https://github.com/user-attachments/assets/55b9bfdf-0f5f-40da-92fd-c5772c61619b)


Could you please check? Also, let's make sure this will work next year, I assume 2024 will be available in the year configuration, right?

Thanks

2024-10-29 11:32 UTC, eperedo commented
> @eperedo if you select 2000 - 2023 period, it gives you an array out of length exception:

Can you show me the configuration. I've executed an analysis from 2020 to 2023 without any errors. 
[Data-Quality.webm](https://github.com/user-attachments/assets/86cc2f4a-a270-4224-85b7-79784dc032b1)

> Also, let's make sure this will work next year, I assume 2024 will be available in the year configuration, right?

Start/End date dropdowns will display all the years from 2020 to current year + 1. 

![image](https://github.com/user-attachments/assets/9a760169-6bed-4635-b194-2a126ab8b7dc)

2024-10-31 07:29 UTC, Ramon-Jimenez requested changes
Thanks @eperedo . Additional tweaks after some testing, the change has some deeper implications that we didn't think of:

- The info message shows also for existing reports that were configured for Global:

![image](https://github.com/user-attachments/assets/2481c623-91f8-4883-b011-9e999655bf1d)

We should only show the message if the analysis have not been run, for the analysis that have already been run for Global in the past, we should not show that message.

- If you don't select any country and click on Save Config Analysis, the Error pop-up at the bottom shows following technical message:

![image](https://github.com/user-attachments/assets/cfe28100-d01e-4a2f-8a39-2fd812ccd449)

We should show 'At least one organisation unit must be specified' in that pop-up.

- Since by default no OrgUnit will be selected, we should not allow anymore to move along the Steps unless the Configuration tab has some valid values. Therefore, if you click on 'NEXT' without any OrgUnit selected, or try to navigate to any of the steps in the step selector without any OrgUnit selected, same pop-up at the bottom showing ''At least one organisation unit must be specified' should appear.

- Last, but not least, if an OrgUnit is selected BUT you haven't clicked in Save Config analysis, and you try to click on 'NEXT' or navigate to any of the steps in the step selecttor, a pop-up at the bottom should say something like 'You must save the Analysis configuration before running any step'

Please, reach out to me in Slack if any of the above are unclear.

2025-01-10 10:40 UTC, merged