Feat: Table actions with confirmation modal
EyeSeeTea/data-quality-dev pull request #7
Opened 2024-02-12 10:58 UTC by mariaozamiz

### :pushpin: References

-   **Issue:** Closes:
[Create Delete/Mark as complete Analysis using the confirmation dialog component](https://app.clickup.com/t/8693n2u72)

### :memo: Implementation

Added UI for row actions, including a confirmation dialog in case the user wants to delete a row. Need further connection to data and logic.

### :video_camera: Screenshots/Screen capture

<img width="911" alt="Captura de pantalla 2024-02-09 a las 18 00 25" src="https://github.com/EyeSeeTea/data-quality-dev/assets/55712984/bf74b775-d4c9-42b2-8d38-d4c8a132620f">
<img width="286" alt="Captura de pantalla 2024-02-09 a las 18 00 33" src="https://github.com/EyeSeeTea/data-quality-dev/assets/55712984/d65ba60d-61a3-4af9-903b-862fe91cc21d">

### :fire: Notes to the tester

Test this at dashboard page clicking on the three-point menu at the end of every row.

2024-02-13 15:50 UTC, eperedo requested changes
Thanks @mariaozamiz! Just a typo and we're good to go.

2024-02-14 13:25 UTC, eperedo requested changes

2024-02-14 13:25 UTC, eperedo commented on src/webapp/pages/dashboard/hooks/useDashboard.tsx
> +    const onStatingAnalysis = () => {};
Sorry @mariaozamiz! Here is the typo!

2024-02-14 20:32 UTC, eperedo approved these changes

2024-02-15 06:57 UTC, Ramon-Jimenez approved these changes
All good, thx @mariaozamiz

2024-02-15 06:57 UTC, merged